server:
  port: 80

spring:
  zipkin:
    base-url: http://110.42.214.187:9411
    sleuth:
      sampler:
        probability: 1 #样本采集量，默认为0.1，为了测试这里修改为1，正式环境一般使用默认值
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true #是否向注册中心注册自己
    fetchRegistry: true #是否从注册中心抓取已有的注册信息 默认true，集群必须设置为true
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      #单机版
      #defaultZone: http://localhost:7001/eureka
      #集群版
      defaultZone: http://110.42.214.187:7001/eureka,http://110.42.214.187:7002/eureka
  instance:
    instance-id: order80
    prefer-ip-address: true