server:
  port: 80

spring:
  application:
    name: cloud-consumerconsul-order80
  cloud:
    consul:
      host: 110.42.214.187
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
