server:
  port: 3344
spring:
  application:
    name: cloud-config-center  # 注册进eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/whyhardpickname/springcloud-config.git  # 远程仓库上配置文件的地址
          username: whyhardpickname
          password: Pw143924
          skip-ssl-validation: true
          default-label: main
          search-paths:
            - springcloud-config
      discovery:
        enabled: true
      enabled: true
# ============ eureka client ===========
eureka:
  # 设置控制台显示的服务路径
  instance:
    instance-id: configCenter3344
    prefer-ip-address: true # 访问地址可以显示ip
    # Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认是30秒）
    lease-renewal-interval-in-seconds: 30
    # Eureka 服务端在收到最后一次心跳后等待时间上线，单位为秒（默认是90秒），超时将剔除服务
    lease-expiration-duration-in-seconds: 90
  client:
    # 表示是否将自己注册进eurekaServer,默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true.单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      # 本机入住eurekaServer 地址
      #defaultZone: http://localhost:7001/eureka  # 单机版
      defaultZone: http://110.42.214.187:7001/eureka,http://110.42.214.187:7002/eureka # 集群版

