server:
  port: 7002

# 单机版
eureka:
  instance:
    hostname: 110.42.214.187  #eureka服务端的实例名字
    prefer-ip-address: true
    instance-id: 110.42.214.187:7002
  client:
    register-with-eureka: false    #表示不向注册中心注册自己
    fetch-registry: false   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://110.42.214.187:7001/eureka/